import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import OpenAI from "openai";

dotenv.config();
const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

app.post("/mentor", async (req, res) => {
  try {
    const { question, profile } = req.body;
    if (!question) return res.status(400).json({ error: "No question provided" });

    const prompt = `
You are a helpful AI career mentor. Answer the user's question concisely and professionally.
User profile: ${JSON.stringify(profile)}
Question: ${question}
`;

    const completion = await openai.chat.completions.create({
      model: "gpt-4",
      messages: [
        { role: "system", content: "You are a helpful career mentor." },
        { role: "user", content: prompt },
      ],
      max_tokens: 400,
    });

    const answer = completion?.choices?.[0]?.message?.content;
    if (!answer) {
      console.error("No answer returned from OpenAI:", completion);
      return res.status(500).json({ error: "No response generated by AI" });
    }

    res.json({ answer });

  } catch (err) {
    console.error("OpenAI error:", err);
    res.status(500).json({ error: "Failed to generate response" });
  }
});

app.listen(PORT, () => console.log(`AI Mentor running at http://localhost:${PORT}`));
